### ISSUE TITLE
Callback names violate API convention

### ISSUE THREAD

**Issue by Desour** [mt-mods/wield_events#2]
Haven't used the mod. But I want to inform you that the callbacks might break in future minetest versions:

https://github.com/minetest/minetest/blob/dde8f0e20af9fd3c76a8bcda3394fb1bf37824c6/doc/lua_api.md?plain=1#L8638-L8641
>    _custom_field = whatever,
>    -- Add your own custom fields. By convention, all custom field names
>    -- should start with `_` to avoid naming collisions with future engine
>    -- usage.

**Comment by wsor4035** [comment]
while an issue, half (didnt measure, spitballing) the minetest ecosystem also has this issue

**Comment by BuckarooBanzay** [comment]
> Haven't used the mod. But I want to inform you that the callbacks might break in future minetest versions:

i'm aware of that, but decided to go the way every other mod goes: just use whatever name fits :shrug: 

will revisit that decision when/if the api might conflict with the local names

**Comment by Desour** [comment]
(Wrong label. This isn't a question, it's a warning. ;))

AFAIK, most mods that add something to the item def use the mod name as prefix (which is actually important if you don't only want compatibility with the engine, but also with other mods). I.e. ideally `on_step` should be `_wield_events_on_step`.
Don't take bad or old mods as example.
